// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProposalApi.Data;

#nullable disable

namespace ProposalApi.Data.Migrations
{
    [DbContext(typeof(ProposalDbContext))]
    [Migration("20250930012007_StatusFix2")]
    partial class StatusFix2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProposalApi.Proposal.Model.ProposalStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProposalStatusLookup", "bank");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = -2,
                            Name = "UnderReview"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("ProposalApi.Proposal.Models.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProposalStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProposalStatusLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Requested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("ProposalStatusLookupId");

                    b.ToTable("Proposals", "bank");
                });

            modelBuilder.Entity("ProposalApi.Proposal.Models.Proposal", b =>
                {
                    b.HasOne("ProposalApi.Proposal.Model.ProposalStatusLookup", "ProposalStatusLookup")
                        .WithMany()
                        .HasForeignKey("ProposalStatusLookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposalStatusLookup");
                });
#pragma warning restore 612, 618
        }
    }
}
