# This is a generated file. Not intended for manual editing.
services:
  client.api:
    build:
      context: "C:\\Users\\tgcla\\RiderProjects\\PBanco\\src"
      dockerfile: "Services/Clients/Clients.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57458"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "client.api:dev"
    ports:
    - "127.0.0.1:57058:57000"
    - "127.0.0.1:57258:57200"
    - "127.0.0.1:57458:57458"
    volumes:
    - "C:\\Users\\tgcla\\RiderProjects\\PBanco\\src\\Services\\Clients\\Clients.API:/app:rw"
    - "C:\\Users\\tgcla\\RiderProjects\\PBanco:/src:rw"
    - "C:\\Users\\tgcla\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\tgcla\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.2.2.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\tgcla\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\tgcla\\AppData\\Local\\JetBrains\\Rider2025.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_10_04_21_33_59:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  credit-card.api:
    build:
      context: "C:\\Users\\tgcla\\RiderProjects\\PBanco\\src"
      dockerfile: "Services/CreditCard/CreditCard.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57459"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "credit-card.api:dev"
    ports:
    - "127.0.0.1:57059:57000"
    - "127.0.0.1:57259:57200"
    - "127.0.0.1:57459:57459"
    volumes:
    - "C:\\Users\\tgcla\\RiderProjects\\PBanco\\src\\Services\\CreditCard\\CreditCard.API:/app:rw"
    - "C:\\Users\\tgcla\\RiderProjects\\PBanco:/src:rw"
    - "C:\\Users\\tgcla\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\tgcla\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.2.2.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\tgcla\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\tgcla\\AppData\\Local\\JetBrains\\Rider2025.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_10_04_21_33_59:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  proposal.api:
    build:
      context: "C:\\Users\\tgcla\\RiderProjects\\PBanco\\src"
      dockerfile: "Services/Proposal/Proposal.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57460"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "proposal.api:dev"
    ports:
    - "127.0.0.1:57060:57000"
    - "127.0.0.1:57260:57200"
    - "127.0.0.1:57460:57460"
    volumes:
    - "C:\\Users\\tgcla\\RiderProjects\\PBanco\\src\\Services\\Proposal\\Proposal.API:/app:rw"
    - "C:\\Users\\tgcla\\RiderProjects\\PBanco:/src:rw"
    - "C:\\Users\\tgcla\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\tgcla\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.2.2.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\tgcla\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\tgcla\\AppData\\Local\\JetBrains\\Rider2025.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_10_04_21_33_59:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
